// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Speedometer Green

#ifndef _SPEEDOMETER_GREEN_UI_H
#define _SPEEDOMETER_GREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Needle1R_Animation(lv_obj_t * TargetObject, int delay);
void Needle2R_Animation(lv_obj_t * TargetObject, int delay);
void Needle3R_Animation(lv_obj_t * TargetObject, int delay);
void Needle4R_Animation(lv_obj_t * TargetObject, int delay);
void Needle5R_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Needle1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Needle2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Needle3;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Needle4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Needle5;
extern lv_obj_t * ui_ring;
extern lv_obj_t * ui_Labelkm;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_green_png);    // assets/Green.png
LV_IMG_DECLARE(ui_img_needle_png);    // assets/Needle.png
LV_IMG_DECLARE(ui_img_ringbig_png);    // assets/RingBig.png
LV_IMG_DECLARE(ui_img_needlea_png);    // assets/Needlea.png
LV_IMG_DECLARE(ui_img_ring2_png);    // assets/Ring2.png
LV_IMG_DECLARE(ui_img_needle3_png);    // assets/Needle3.png
LV_IMG_DECLARE(ui_img_ringbig2_png);    // assets/RingBig2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
