// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Speedometer Green

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_green_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 11);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image1, 6);

    ui_Needle1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Needle1, &ui_img_needle_png);
    lv_obj_set_width(ui_Needle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Needle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Needle1, 93);
    lv_obj_set_y(ui_Needle1, 61);
    lv_obj_set_align(ui_Needle1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle1, 0, 1);
    lv_img_set_angle(ui_Needle1, 300);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_ringbig_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 93);
    lv_obj_set_y(ui_Image3, 13);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Needle2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Needle2, &ui_img_needlea_png);
    lv_obj_set_width(ui_Needle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Needle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Needle2, -57);
    lv_obj_set_y(ui_Needle2, -74);
    lv_obj_set_align(ui_Needle2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle2, 0, 3);
    lv_img_set_angle(ui_Needle2, 3000);

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_ring2_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -74);
    lv_obj_set_y(ui_Image5, -71);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image5, 200);

    ui_Needle3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Needle3, &ui_img_needlea_png);
    lv_obj_set_width(ui_Needle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Needle3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Needle3, -57);
    lv_obj_set_y(ui_Needle3, 89);
    lv_obj_set_align(ui_Needle3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle3, 1, 0);
    lv_img_set_angle(ui_Needle3, 600);

    ui_Image7 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image7, &ui_img_ring2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -74);
    lv_obj_set_y(ui_Image7, 87);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Needle4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Needle4, &ui_img_needle3_png);
    lv_obj_set_width(ui_Needle4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Needle4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Needle4, -121);
    lv_obj_set_y(ui_Needle4, -19);
    lv_obj_set_align(ui_Needle4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle4, 0, 1);
    lv_img_set_angle(ui_Needle4, 1850);

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_ringbig2_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -143);
    lv_obj_set_y(ui_Image9, -19);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Needle5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Needle5, &ui_img_needle3_png);
    lv_obj_set_width(ui_Needle5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Needle5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Needle5, -125);
    lv_obj_set_y(ui_Needle5, 33);
    lv_obj_set_align(ui_Needle5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle5, 0, 5);
    lv_img_set_angle(ui_Needle5, 1250);

    ui_ring = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ring, &ui_img_ringbig2_png);
    lv_obj_set_width(ui_ring, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ring, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ring, -145);
    lv_obj_set_y(ui_ring, 40);
    lv_obj_set_align(ui_ring, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ring, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ring, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelkm = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelkm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelkm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelkm, 94);
    lv_obj_set_y(ui_Labelkm, 60);
    lv_obj_set_align(ui_Labelkm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelkm, "0");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -144);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SPEEDOMETER CAR DASHBOARD");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
