esphome:
  name: esp32-bikedash-esphome-client
  friendly_name: esp32_bikedash_esphome_client

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.178.45
    gateway: 192.168.178.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Bikedash-Esphome-Client"
    password: "XXXXXXXX"

captive_portal:
    
# http
web_server:
 port: 80


wifi_now:
  channel: 2
  peers:
    - id: collector
      bssid: <Mac ID Device B>
